# Generated by Django 3.2.8 on 2021-10-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('liked_posts', models.ManyToManyField(blank=True, related_name='likers', to='forums.Post')),
            ],
        ),
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
