# Generated by Django 3.2.8 on 2021-10-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_auto_20211030_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('content', models.CharField(max_length=1024)),
                ('indivcomment_id', models.IntegerField()),
                ('user', models.CharField(max_length=1024)),
            ],
        ),
        migrations.DeleteModel(
            name='Commentor',
        ),
    ]
