# Generated by Django 3.2.8 on 2021-11-01 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0009_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
