# Generated by Django 3.2.4 on 2021-09-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=64, null=True)),
                ('description', models.TextField()),
                ('level', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
    ]
