# Generated by Django 3.2.4 on 2021-09-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_inquiry_student_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='comment',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
