# Generated by Django 3.2.4 on 2021-09-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210909_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qualifications',
            field=models.TextField(null=True),
        ),
    ]
