# Generated by Django 3.2.4 on 2021-09-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_profile_qualifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_user', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('score', models.IntegerField()),
                ('feedback', models.TextField(null=True)),
            ],
        ),
    ]
