# Generated by Django 3.2.4 on 2021-09-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_rating_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('sender', models.CharField(max_length=64)),
                ('receiver', models.CharField(max_length=64)),
                ('content', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='announcement',
            field=models.TextField(default=None, null=True),
        ),
    ]
