# Generated by Django 3.2.4 on 2021-09-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_chat_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='contact',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
