# Generated by Django 3.2.4 on 2021-09-22 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210921_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='message_id',
        ),
        migrations.AddField(
            model_name='messages',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
