# Generated by Django 3.2.4 on 2021-09-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20210922_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
