# Generated by Django 3.2.4 on 2021-09-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_messages_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='status',
            new_name='read',
        ),
    ]
