# Generated by Django 3.2.4 on 2021-09-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_rename_status_messages_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='read',
            field=models.BooleanField(default=None),
        ),
    ]
