# Generated by Django 3.2.4 on 2021-09-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_messages_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_id',
            field=models.IntegerField(default=None),
        ),
    ]
