# Generated by Django 3.2.4 on 2021-09-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_messages_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_id',
            field=models.IntegerField(null=True),
        ),
    ]
