# Generated by Django 3.2.4 on 2021-10-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_alter_messages_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
