# Generated by Django 3.2.4 on 2021-10-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20211003_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='file',
        ),
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
