# Generated by Django 3.2.4 on 2021-10-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_timeslots'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslots',
            name='customer',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='timeslots',
            name='limitpax',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='timeslots',
            name='timeslotid',
            field=models.IntegerField(default=None),
        ),
    ]
