# Generated by Django 3.2.4 on 2021-10-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_auto_20211006_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslots',
            name='timeslotid',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
