# Generated by Django 3.2.4 on 2021-10-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_alter_timeslots_timeslotid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslots',
            name='timeslotid',
        ),
    ]
