# Generated by Django 3.2.4 on 2021-10-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_remove_timeslots_timeslotid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslots',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='timeslots',
            name='limitpax',
        ),
    ]
