# Generated by Django 3.2.4 on 2021-10-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_auto_20211006_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timeslots',
        ),
    ]
