# Generated by Django 3.2.4 on 2021-10-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_delete_timeslots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingid', models.IntegerField()),
                ('customer', models.CharField(default=None, max_length=64, null=True)),
                ('timeslotid', models.IntegerField(default=None, null=True)),
                ('timeslot', models.CharField(default=None, max_length=1024, null=True)),
                ('selected', models.BooleanField(default=None)),
                ('limitpax', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
