# Generated by Django 3.2.4 on 2021-10-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_timeslots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='message_id',
        ),
    ]
