# Generated by Django 3.2.4 on 2021-10-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_remove_messages_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.IntegerField(default=None, null=True)),
                ('customer', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='timeslots',
            name='customer',
        ),
    ]
