# Generated by Django 3.2.8 on 2021-10-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_auto_20211006_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=64, null=True)),
                ('info', models.CharField(default=None, max_length=1024, null=True)),
                ('category', models.CharField(default=None, max_length=64, null=True)),
            ],
        ),
    ]
