# Generated by Django 3.2.8 on 2021-10-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notifid',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='read',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='notifications',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
