# Generated by Django 3.2.8 on 2021-10-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_auto_20211008_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='media'),
        ),
    ]
