# Generated by Django 3.2.8 on 2021-11-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0039_profile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='student', max_length=64)),
                ('user', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
